pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - docs/*

pr: none    

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.0.100'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.0.0'
  inputs:
    version: '2.0.0'

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud analysis'
  inputs:
    SonarCloud: 'SonarCloud connection 1'
    organization: '$(organization)'
    projectKey: '$(projectKey)'
    projectName: '$(projectName)'
    projectVersion: '$(Build.BuildNumber)'
    extraProperties: |
     sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.opencover.xml
     sonar.exclusions=**/wwwroot/lib/**/*
  condition: |
    and
    (
    succeeded(),
    eq(variables['Build.Reason'], 'IndividualCI'),
    eq(variables['System.IndividualCI.TargetBranch'], 'failed-test')
    )

- script: 'ls'
  displayName: 'ls command test'
  
- script: |
    ls
    pwd
  displayName: 'multi line command test'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Install ReportGenerator'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-reportgenerator-globaltool'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

- script: |
    reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines
  displayName: 'Create code coverage report'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.0.0'
  inputs:
    version: '2.0.0'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud code analysis'
  condition: |
    and
    (
    succeeded(),
    eq(variables['Build.Reason'], 'IndividualCI'),
    eq(variables['System.IndividualCI.TargetBranch'], 'failed-test')
    )

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud quality gate results'
  condition: |
    and
    (
    succeeded(),
    eq(variables['Build.Reason'], 'IndividualCI'),
    eq(variables['System.IndividualCI.TargetBranch'], 'failed-test')
    )

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()